services:
  auth-service:
    build: .
    ports:
      - "3009:3009"
    environment:
     - JWT_SECRET=mi_clave_proyecto_final  # 🔥 Definido aquí
     - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - auth-mongo

  auth-mongo:
    image: mongo:7
    ports:
      - "27025:27017"
    environment:
      - MONGO_INITDB_DATABASE=auth_db
    volumes:
      - auth_data:/data/db

volumes:
  auth_data:
