services:
  mongodb:
    image: mongo:latest
    container_name: Api-1-Users
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: muXaVfzFMhAtOHixFMWPqlFNbkLxZRTI
    ports:
      - "27025:27017"
    volumes:
      - ./mongodb_data:/data/db
